- menu_name: "Servicios"

- name: "Contactar"
  url: "/contact/"
  title: "Contactar"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscribirse a RSS"

- name: "Atom"
  url: "/atom.xml"
  title: "Subscribirse a Atom"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap para Google Webmaster Tools"
